apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: go-api
          envFrom:
          - configMapRef:
              name: go-api
          env:
          - name: APP_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: '/healtz'
            initialDelaySeconds: 5
            periodSeconds: 60 # 5